// <auto-generated />
using System;
using BehaviorTracker.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BehaviorTracker.Repository.Migrations
{
    [DbContext(typeof(BehaviorTrackerDatabaseContext))]
    partial class BehaviorTrackerDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BehaviorTracker.Repository.Models.Goal", b =>
                {
                    b.Property<long>("GoalKey")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GoalDescription");

                    b.Property<int>("GoalType");

                    b.Property<long>("StudentKey");

                    b.HasKey("GoalKey");

                    b.HasIndex("StudentKey");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.GoalAnswer", b =>
                {
                    b.Property<long>("GoalAnswerKey")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<DateTime>("Date");

                    b.Property<long>("GoalKey");

                    b.Property<string>("Notes");

                    b.HasKey("GoalAnswerKey");

                    b.HasIndex("GoalKey");

                    b.ToTable("GoalAnswers");
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.GoalAvailableAnswer", b =>
                {
                    b.Property<long>("GoalAvailableAnswerKey")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GoalKey");

                    b.Property<string>("OptionValue");

                    b.HasKey("GoalAvailableAnswerKey");

                    b.HasIndex("GoalKey");

                    b.ToTable("GoalAvailableAnswer");
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.Student", b =>
                {
                    b.Property<long>("StudentKey")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StudentFirstName");

                    b.Property<string>("StudentLastName");

                    b.HasKey("StudentKey");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.Goal", b =>
                {
                    b.HasOne("BehaviorTracker.Repository.Models.Student", "Student")
                        .WithMany("Goals")
                        .HasForeignKey("StudentKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.GoalAnswer", b =>
                {
                    b.HasOne("BehaviorTracker.Repository.Models.Goal", "Goal")
                        .WithMany("GoalAnswers")
                        .HasForeignKey("GoalKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BehaviorTracker.Repository.Models.GoalAvailableAnswer", b =>
                {
                    b.HasOne("BehaviorTracker.Repository.Models.Goal", "Goal")
                        .WithMany("AvailableAnswers")
                        .HasForeignKey("GoalKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
